name: iOS deploy

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Arc Clone
      run: |
           cd work && ../scripts/applyPatches.sh
           cd ..
           git clone https://github.com/Anuken/Arc.git
           cd work
           ls
           mkdir ios/libs
           cp ../Arc/natives/natives-ios/libs/libarc.a ./ios/libs/
           cp ../Arc/natives/natives-freetype-ios/libs/libarc-freetype.a ./ios/libs/
    - name: iOS deploy
      run: |
           cd work
           ./gradlew ios:deploy -Pbuildversion=mindustryX-ios-b147
    - name: Upload file
      uses: actions/upload-artifact@v4
      with:
          name: ios-build
          path: ios/build/robovm/IOSLauncher.ipa
